<!--Generated by Weblogic Workshop-->
<%@page language="java" contentType="text/html;charset=UTF-8" %>

<%@page import="com.kizsoft.commons.commons.user.Group" %>
<%@page import="com.kizsoft.commons.commons.user.User" %>
<%@page import="com.kizsoft.commons.commons.util.ReadInfo" %>
<%@page import="com.kizsoft.commons.commons.util.ReadInfoManager" %>
<%@page import="com.kizsoft.commons.component.entity.FieldEntity" %>
<%@page import="com.kizsoft.commons.uum.pojo.Owner" %>
<%@page import="com.kizsoft.commons.uum.service.IUUMService" %>
<%@page import="com.kizsoft.commons.uum.utils.UUMContend" %>
<%@page import="java.util.Date" %>

<%@taglib prefix="template" uri="/WEB-INF/struts-template.tld" %>
<%@taglib prefix="html" uri="/WEB-INF/oa-html.tld" %>
<%@taglib prefix="oa" uri="/WEB-INF/oa.tld" %>

<%//用户登陆验证
	if (session.getAttribute("userInfo") == null) {
		response.sendRedirect(request.getContextPath() + "/login.jsp");
	}
	String contextPath = "/".equals(request.getContextPath()) ? "" : request.getContextPath();
	User userInfo = (User) session.getAttribute("userInfo");
	String userID = userInfo.getUserId();
	String userName = userInfo.getUsername();
	Group groupInfo = userInfo.getGroup();
	String groupID = groupInfo.getGroupId();
	String creator = getAttr(request,"issuemanid");

	Integer days = new Integer(3);
	pageContext.setAttribute("effectDays", days);
	String unid = request.getParameter("appId");
	String content = getAttr(request,"content");

	boolean readFlag = false;
	ReadInfoManager readInfoManager = new ReadInfoManager();
	readFlag = readInfoManager.getReadInfoFlag_User(unid, userID, groupID); //个人
	if (!readFlag) {
		ReadInfo readInfo = new ReadInfo();
		readInfo.setId(unid);
		readInfo.setReadDepartmentID(groupID);
		readInfo.setReadManID(userID);
		readInfo.setReadManName(userName);
		readInfo.setReadTime(new Date());
		readInfoManager.addReadInfo(readInfo);
	}
%>
<%!
	public String getAttr(HttpServletRequest request,String name){
		String temp="";
		FieldEntity tempentity = (FieldEntity) request.getAttribute(name);
		if (tempentity == null || tempentity.getValue() == null || "".equals(tempentity.getValue())) {
		} else {
			temp = (String) tempentity.getValue();
		}
		return temp;
	}
%>
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>台州市公安局.最多跑一次网上办</title>
	<link href="<%=request.getContextPath()%>/resources/css/css.css" rel="stylesheet" type="text/css">
	<script language="javascript" type="text/javascript" charset="utf-8" src="<%=contextPath%>/resources/js/jquery/jquery-1.11.0.min.js"></script>

	<script language="javascript" type="text/javascript" charset="utf-8" src="<%=contextPath%>/resources/js/datepicker/WdatePicker.js"></script>
	<script language="javascript" type="text/javascript" charset="utf-8" src="<%=contextPath%>/resources/js/layer/layerFunction.js"></script>

<style>
	
</style>
<body>
<script language="javascript">
	//查看附件
		function showAttach(uuid){
			openIframeWin({
				url:'<%=request.getContextPath()%>/resources/jsp/signature/showAttach.jsp?uuid='+uuid,
				title:"查看附件",
				width:"1000px",
				height:"750px"
			});
		}
	function editDoc() {
		var getdocID = document.all.unid.value;
		window.location.href = "<%=request.getContextPath()%>/edit?xmlName=sharebulletin&appId=" + getdocID;
	}
</script>
<script language="javascript">
	function readinfo() {
		window.location.href = "<%=request.getContextPath()%>/view?xmlName=sharebulletin&appId=<%=unid%>&showflag=1";
	}
</script>
<input type="hidden" name="moduleId" value="sharebulletin" />
<html:hidden name="unid" />
<TABLE CLASS="outline" border="0" align=center bgcolor="#000000" WIDTH="100%" CELLSPACING=0 CELLPADDING=0 class="hjssz">
	<TR VALIGN=top>
		<TD bgcolor="#808080" WIDTH="100%">
			<script language="Javascript" src="<%=request.getContextPath ()%>/resources/js/formup.js"></script>
			<table border="0" width="97%" class="showpage">
				<tr>
					<td>
						<%if (creator.equals(userID)) {%>
						<div align="right">
							<input type="button" name="printer" class="formbutton" value="修  改" onclick="editDoc();"/>
						</div>
						<%}%>
					</td>
				</tr>
				<tr> 
					<td height="600px" valign="top">
						<div align="center">
							<font style="font-size:16pt"><b><html:write name="title"/></b></font>
							<br><font style="font-size:12pt">(<html:write name="issuetime" format="yyyy-MM-dd"/> )</font>
							<HR WIDTH="100%" SIZE=2 ALIGN=center COLOR="#000000" NOSHADE/>
						</div>
						<br/><br/>
						<table border="0" width="100%" CELLSPACING=0 CELLPADDING=0>
							<tr>
								<td class="content">
									<span style="font-size:12pt;line-height: 24px;"><%=content%></span>
								</td>
							</tr>
						</table>
					</td>

				</tr>
				<tr>
					<td>
						<div style="font-size:9pt">
							附件：
							<html:attachment moduleid="sharebulletin" unid="unid" type="content2" showdelete="false"/>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<HR WIDTH="100%" SIZE=2 ALIGN=left COLOR="#C0C0C0">
						<div align="right" style="font-size:12pt">
							发布人：<html:write name="issueman"/>　　
						</div>
					</td>
				</tr>
				<%if (creator.equals(userID)) {%>
				<tr>
					<td>
						<input type="button" name="printer" value="查看阅读情况" onclick="readinfo();" style="width:100px">
						<br>
						<% String showflag = request.getParameter("showflag");
							if (showflag != null) {
								if (showflag.equals("1")) { %>
						<jsp:include page="/sharebulletin/readinfo_bulletin.jsp">
							<jsp:param name="id" value="<%=unid%>"/>
						</jsp:include>
						<% }
						} %>
					</td>
				</tr>
				<%}%>
			</TABLE>
			<script language="Javascript" src="<%=request.getContextPath ()%>/resources/js/formdown.js"></script>

		</td>
	</tr>
</TABLE>
</body>
</html>	
<!--索思奇智版权所有-->