<!--Generated by Weblogic Workshop-->
<%@page language="java" contentType="text/html;charset=UTF-8" %>

<%@page import="com.kizsoft.commons.commons.user.Group" %>
<%@page import="com.kizsoft.commons.commons.user.User" %>
<%@page import="com.kizsoft.commons.commons.util.ReadInfo" %>
<%@page import="com.kizsoft.commons.commons.util.ReadInfoManager" %>
<%@page import="com.kizsoft.commons.component.entity.FieldEntity" %>
<%@page import="com.kizsoft.commons.uum.pojo.Owner" %>
<%@page import="com.kizsoft.commons.uum.service.IUUMService" %>
<%@page import="com.kizsoft.commons.uum.utils.UUMContend" %>
<%@page import="java.util.Date" %>

<%@taglib prefix="template" uri="/WEB-INF/struts-template.tld" %>
<%@taglib prefix="html" uri="/WEB-INF/oa-html.tld" %>
<%@taglib prefix="oa" uri="/WEB-INF/oa.tld" %>

<%//用户登陆验证
	if (session.getAttribute("userInfo") == null) {
		response.sendRedirect(request.getContextPath() + "/login.jsp");
	}
	User userInfo = (User) session.getAttribute("userInfo");
	String userID = userInfo.getUserId();
	Group groupInfo = userInfo.getGroup();
	String groupID = groupInfo.getGroupId();
	String creator = getAttr(request,"issuemanid");

	Integer days = new Integer(3);
	pageContext.setAttribute("effectDays", days);
	String unid = request.getParameter("appId");
	String content = getAttr(request,"content");

	boolean readFlag = false;
	ReadInfoManager readInfoManager = new ReadInfoManager();
	readFlag = readInfoManager.getReadInfoFlag_User(unid, userID, groupID); //个人
	if (!readFlag) {
		ReadInfo readInfo = new ReadInfo();
		readInfo.setId(unid);
		readInfo.setReadDepartmentID(groupID);
		readInfo.setReadManID(userID);
		readInfo.setReadTime(new Date());
		readInfoManager.addReadInfo(readInfo);
	}
%>
<%!
	public String getAttr(HttpServletRequest request,String name){
		String temp="";
		FieldEntity tempentity = (FieldEntity) request.getAttribute(name);
		if (tempentity == null || tempentity.getValue() == null || "".equals(tempentity.getValue())) {
		} else {
			temp = (String) tempentity.getValue();
		}
		return temp;
	}
%>
<%
	String templatename = (String) session.getAttribute("templatename");
	String templatestr = "/resources/template/" + templatename + "/template.jsp";
	if (templatename == null || "".equals(templatename)) {
		templatestr = "/resources/jsp/template.jsp";
	}
%>
<template:insert template="<%=templatestr%>">
<template:put name='title' content='公告信息' direct='true'/>
<%String str = "<a class=\"menucur\" href=\"sharebulletin\">公告信息</a>";%>
<template:put name='moduleNav' content='<%=str%>' direct='true'/>
<template:put name='content'>

<script language="javascript">
	function editDoc() {
		var getdocID = document.all.unid.value;
		window.location.href = "<%=request.getContextPath()%>/edit?xmlName=sharebulletin&appId=" + getdocID;
	}
</script>
<script language="javascript">
	function readinfo() {
		window.location.href = "<%=request.getContextPath()%>/view?xmlName=sharebulletin&appId=<%=unid%>&showflag=1";
	}
</script>
<style>
	.sdsdsd h1,.sdsdsd span{
		word-wrap:break-word;
		white-space: pre-wrap;
	}
	.sdsdsd table{
		margin: 0px;
		width: 100%;
	}
	.sdsdsd table tr td img{
		width: 100%;
		display: block;
	}
</style>
<input type="hidden" name="moduleId" value="sharebulletin" />
<html:hidden name="unid" />
<TABLE CLASS="outline" border="0" align=center bgcolor="#000000" WIDTH="100%" CELLSPACING=0 CELLPADDING=0 class="hjssz">
	<TR VALIGN=top>
		<TD bgcolor="#808080" WIDTH="100%">
			<div align="center">
			<table border="0" cellpadding="0" cellspacing="0" style="MARGIN-LEFT: 20px;MARGIN-BOTTOM: 20px; MARGIN-RIGHT: 20px; MARGIN-TOP: 20px">
			<tr><td valign="top">
				<table border="0" cellpadding="0" cellspacing="0"><tr>
				<td bgcolor="#ffffff" style="BORDER-BOTTOM: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-TOP: #000000 1px solid" nowrap valign="center">
				<div align="center" style="MARGIN-LEFT: 20px;MARGIN-BOTTOM: 30px; MARGIN-RIGHT: 20px; MARGIN-TOP: 40px">
				<table border="0" cellpadding="0" cellspacing="0" class="sdsdsd">
				<tr><td  width="100%" valign="top">


			<table border="0" width="97%" class="showpage">
				<tr>
					<td>
						<%if (creator.equals(userID)) {%>
						<div align="right">
							<input type="button" name="printer" class="formbutton" value="修  改" onclick="editDoc();"/>
						</div>
						<%}%>
					</td>
				</tr>
				<tr> 
					<td height="600px" valign="top">
						<div align="center">
							<font style="font-size:16pt"><b><html:write name="title"/></b></font>
							<br><font style="font-size:12pt">(
							<html:write name="issuetime" format="yyyy-MM-dd"/> )</font>
							<HR WIDTH="100%" SIZE=2 ALIGN=center COLOR="#000000" NOSHADE/>
						</div>
						<br/><br/>
						<table border="0" width="100%" CELLSPACING=0 CELLPADDING=0>
							<tr>
								<td class="content">
									<span style="font-size:12pt;line-height: 24px;"><%=content%></span>
								</td>
							</tr>
						</table>
					</td>

				</tr>
				<tr>
					<td>
						<div style="font-size:9pt">
							附件：
							<html:attachment moduleid="sharebulletin" unid="unid" type="content2" showdelete="false"/>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<HR WIDTH="100%" SIZE=2 ALIGN=left COLOR="#C0C0C0">
						<div align="right" style="font-size:12pt">
							发布人：<html:write name="issueman"/>　　
						</div>
					</td>
				</tr>

				<tr>
					<td>
						<input type="button" name="printer" value="查看阅读情况" onclick="readinfo();" style="width:100px">
						<br>
						<% String showflag = request.getParameter("showflag");
							if (showflag != null) {
								if (showflag.equals("1")) { %>
						<jsp:include page="/resources/jsp/readinfo_bulletin.jsp">
							<jsp:param name="id" value="<%=unid%>"/>
						</jsp:include>
						<% }
						} %>
					</td>
				</tr>
			</TABLE>
			</td>
			</tr>
			</table>
			</div>
			</td>
				<center>
					<td width="3" valign="top">
						<table border="0" cellpadding="0" cellspacing="0" width="100%" height="100%">
							<tr>
							<td width="3" height="3"></td>
							</tr>
							<tr>
								<td width="100%" bgcolor="#000000" height="*">&nbsp;</td>
							</tr>
						</table>
					</td>
				</center>
			</tr>
			</table>
			</td>
			</tr>
			<tr>
				<td valign="top" height="3">
					<table border="0" cellpadding="0" cellspacing="0" width="100%" height="100%">
					<tr>
						<td width="3"></td>
							<td bgcolor="#000000"><font style="line-height:1px; FONT-SIZE: 1px" >&nbsp;</font></td>
					</tr>
					</table>
				</td>
			</tr>
			</table>
		</div>

		</td>
	</tr>
</TABLE>

</template:put>
</template:insert>			
<!--索思奇智版权所有-->